# Generated by Django 4.0.5 on 2022-06-05 19:12

import announcements.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', announcements.models.UserManager()),
            ],
        ),
    ]
