# Generated by Django 4.0.5 on 2022-11-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_test_test2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='email',
        ),
    ]
