# Generated by Django 4.0.5 on 2022-11-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_remove_announcement_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Test2',
        ),
    ]
